---
title: "Shiny Team: 60 days"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    theme: paper
    source_code: "https://github.com/schloerke/shinyteamdashboard"
params:
  start:
    label: Start date of report
    value: !r lubridate::today() - lubridate::ddays(60)
    input: date
  # orgs:
  #   label: GitHub organizations
  #   value: tidyverse, r-lib, r-dbi
  #   input: text
  # privacy:
  #   label: Repository Privacy
  #   value: PUBLIC
  #   choices: [PUBLIC]
  #   originalChoices: [PUBLIC, PRIVATE, BOTH]
  repos:
    # - rstudio/pullthat
    # - rstudio/htmldeps
    - r-lib/fastmap
    - r-lib/later
    - ropensci/plotly
    - rstudio-education/gradethis
    - rstudio-education/ymlthis
    - rstudio/bootstraplib
    - rstudio/chromote
    - rstudio/crosstalk
    - rstudio/d3heatmap
    - rstudio/flexdashboard
    - rstudio/gt
    - rstudio/htmltools
    - rstudio/httpuv
    - rstudio/jquerylib
    - rstudio/leaflet
    - rstudio/leaflet.providers
    - rstudio/learnr
    - rstudio/plumber
    - rstudio/pool
    - rstudio/profvis
    - rstudio/promises
    - rstudio/reactlog
    - rstudio/rmarkdown
    - rstudio/sass
    - rstudio/shiny
    - rstudio/shiny-server
    - rstudio/shiny-examples
    - rstudio/shinycannon
    - rstudio/shinycoreci-apps
    - rstudio/shinycoreci
    - rstudio/shinydashboard
    - rstudio/shinyloadtest
    - rstudio/shinymeta
    - rstudio/shinytest
    - rstudio/shinythemes
    - rstudio/shinyvalidate
    - rstudio/sortable
    - rstudio/swagger
    - rstudio/thematic
    - rstudio/websocket
    # - rstudio/yamlthis
editor_options:
  chunk_output_type: console
---

```{r setup, include = FALSE}
library(flexdashboard)
library(gh)
library(jsonlite)
library(lubridate)
library(dplyr)
library(purrr)
library(tibble)
library(codetools) # there was a weird error on connect that needed this
library(DT)
library(shinyteamdashboard)
library(tidyr)
library(sparkline)
library(ggplot2)
library(emo)
on_macos <- (tolower(Sys.info()[["sysname"]]) == "darwin")
gh_colors <- list(
  green = "#2cbe4e",
  red = "#CB2434",
  purple = "#6f42c1")
start <- params$start
duration <- format(today() - start, format = "%d")
# orgs <- scan(text = params$orgs, what = "character", sep = ",", strip.white = TRUE, quiet = TRUE)
# privacy <- normalize_privacy(params$privacy)

repo_infos <-
  params$repos %>%
  # c("rstudio/leaflet", "rstudio/shiny") %>%
  strsplit("/") %>%
  map_dfr(function(orgrepo) {
    tibble(org = orgrepo[[1]], repo = orgrepo[[2]])
  })

# plus1 emoji
p1 <- "\U0001f44d"
```



```{r pr_stats, include=FALSE, cache=on_macos}
options(repos = c(CRAN='https://cloud.r-project.org'))
# pr_data <- tryCatch(
#   map_dfr(orgs, org_pr, privacy = privacy),
#   error = function(e) message(e$content$errors))
pr_data <- repo_infos %>% pmap_dfr(repo_pr)

if (!is.null(pr_data)) {
  prs <- pr_data %>%
    # filter(updated >= start) %>%
    mutate(reviewer = map2(reviews, comments, function(reviews, comments) unique(c(reviews$reviewer, comments$commenter)))) %>%
    select(owner, repo, issue, author, created, updated, reviewer) %>%
    unnest() %>%
    # filter(reviewer != author) %>%
    mutate(
      reviewer = github_user_home(reviewer),
      author = github_user_home(author))

  pr_authors <- prs %>% group_by(author) %>% select(-reviewer) %>% unique() %>% tally(sort = TRUE)
  pr_reviewers <- prs %>% group_by(reviewer) %>% select(-author) %>% unique() %>% tally(sort = TRUE)
  pr_pairs <- prs %>% group_by(author, reviewer) %>% filter(reviewer != author) %>% tally(sort = TRUE)
} else {
  pr_authors <- NULL
  pr_reviewers <- NULL
  pr_pairs <- NULL
}
```

```{r repo_stats, include=FALSE, cache = on_macos}
# repo_data_list <- map(orgs, org_data, privacy)
repo_data_list <- pmap(repo_infos, repo_data)

repo_summary <- map_dfr(repo_data_list, "summary")
issues <- map_dfr(repo_data_list, "issues")
```


`r duration` issue progress
=====================================
```{r issue_progress, cache = on_macos, include = FALSE}
# issue_data <- map_dfr(orgs, issue_progress, start, privacy)
issue_data <- pmap_dfr(repo_infos, repo_issue_progress, start)

issue_data2 <- issue_data %>%
  mutate(
    type = factor(levels = c("issue", "pull_request"),
      case_when(
        type == "Issue" ~ "issue",
        type == "PullRequest" ~ "pull_request")),

    status = factor(levels = c("opened", "closed", "merged", "old"),
      case_when(
        merged >= start ~ "merged",
        closed >= start ~ "closed",
        opened >= start ~ "opened",
        TRUE ~ "old")),
    event = case_when(
      status == "merged" ~ merged,
      status == "closed" ~ closed,
      status == "opened" ~ opened)
  )
```

````{r}
totals <- issue_data2 %>%
  filter(status != "old") %>%
  group_by(type, status) %>%
  tally() %>%
  mutate(n = if_else(status == "closed" | status == "merged", n * -1L, n)) %>%
  na.omit()
```

Row
------------------------------

```{r, include = FALSE}
pr_opened_sum <- totals %>% filter(type == "pull_request", status == "opened") %>% pull("n") %>% sum()
pr_closed_sum <- totals %>% filter(type == "pull_request", (status == "merged" | status == "closed")) %>% pull("n") %>% abs() %>% sum()
pr_change <- totals %>% filter(type == "pull_request") %>% pull("n") %>% sum()
pr_open <- if(is.null(pr_data)) 0 else nrow(pr_data)

issue_opened_sum <- totals %>% filter(type == "issue", status == "opened") %>% pull("n") %>% sum()
issue_closed_sum <- totals %>% filter(type == "issue", status == "closed") %>% pull("n") %>% abs()
issue_change <- totals %>% filter(type == "issue") %>% pull("n") %>% sum()
issue_open <- nrow(issues)
```


### Pull requests opened
```{r}
valueBox(pr_opened_sum, icon = "fa-exclamation-circle")
```

### Pull requests merged / closed
```{r}
valueBox(pr_closed_sum, icon = "ion-merge", color = "info")
```

### Pull requests `r duration` change
```{r}
valueBox(pr_change, icon = "fa-exclamation-circle", color = if (pr_change <= 0) "success" else "danger")
```

### Open pull requests
```{r}
valueBox(pr_open, icon = "fa-exclamation-circle")
```

### Issues opened
```{r}
valueBox(issue_opened_sum, icon = "fa-exclamation-circle", color = "info")
```

### Issues closed
```{r}
valueBox(issue_closed_sum, icon = "fa-times-circle", color = "info")
```


### Issues `r duration` change
```{r}
valueBox(issue_change, icon = "fa-exclamation-circle", color = if (issue_change <= 0) "success" else "danger")
```

### Open issues
```{r}
valueBox(issue_open, icon = "fa-exclamation-circle")
```


Row
-------------------------------------

### `r duration` progess {data-width=1000}

```{r}
issue_progress_table <- issue_data2 %>%
  # Add maintiner to the table
    left_join(mutate(repo_summary, maintainer = desc_maintainer(description)) %>%
              select(repo, maintainer), by = c("package" = "repo")) %>%
  group_by(type, status) %>%
  arrange(event) %>%
  select(owner, package, type, number = issue, status, maintainer, event) %>%
  na.omit()

data_table(
  issue_progress_table,
  list(
    order = list(
      list(6, "desc")  # updated from newest to oldest
    )
  )
)
```

> Issues with status modified (`r start` - `r now()`).

### Issue status

```{r issue_progress_img, fig.width=15, fig.height=9}
issue_progress_running <-
  issue_progress_table %>%
    group_by(type) %>%
    mutate(count = case_when(
      type == "issue" & status == "closed" ~ -1,
      type == "pull_request" &
        (status == "merged" | status == "closed") ~ -1,
      TRUE ~ 1
    )) %>%
    group_by(package, type) %>%
    mutate(running_total = cumsum(count)) %>%
    select(event, running_total, type, package)

min_event_time_is_0 <- issue_progress_running %>%
  group_by(package, type) %>%
  summarize(
    event = min(event),
    running_total = 0
  ) %>%
  select(event, running_total, type, package)

max_event_time <- issue_progress_running %>%
  group_by(package, type) %>%
  summarize(
    event = max(event),
    running_total = running_total[length(running_total)]
  ) %>%
  select(event, running_total, type, package)


dplyr::bind_rows(
  min_event_time_is_0,
  issue_progress_running
) %>%
  ggplot(aes(event, running_total, color = type, linetype = type)) +
    geom_hline(yintercept = 0, col = "grey80")+
    geom_step(size = 1) +
    geom_point(data = dplyr::bind_rows(min_event_time_is_0, max_event_time), size = 1.5) +
    labs(x = NULL, y = "Issues", subtitle = "opened: positive; closed: negative") +
    theme(plot.subtitle = element_text(size = 5), legend.position = "bottom") +
    scale_color_manual(values = c("issue" = "#fc8d62", "pull_request" = "#66c2a5")) +
    scale_linetype_manual(values = c("issue" = "F191", "pull_request" = "solid")) +
    facet_wrap(~package, ncol = 5)

```

> `r start` - `r now()`

Repository summary
=====================================

```{r repo_summary, cache = on_macos}
summary_table <- repo_summary %>%
  rename("package" = "repo") %>%
  mutate(
    weekly_downloads = num_downloads(.$package, "last-week"),
    maintainer = desc_maintainer(description),
    reverse_deps = reverse_dependencies(package),
    dev_deps = desc_dev_deps(description),
    travis_status = travis_status_badge(owner, package),
    appveyor_status = appveyor_status_badge(owner, package),
    cran_status = cran_status_badge(package),
    activity = map2(owner, package, weekly_commits)) %>%
  select(owner, package, maintainer, watchers, reverse_deps, weekly_downloads, open_issues, prs, p1, everything(), -description) %>%
  rename(!!p1 := p1)
```

```{r}
# A custom datatable with a sparkline column
dt <- sparkline_table(
  summary_table,
  list(
    order = list(
      list(7, "desc") # PR number descending sort
    )
  ),
  sparkline_column = which(colnames(summary_table) == "activity"),
  colnames = c("52 week conmmit activity" = "activity")
)
dt
```

Open issues
=====================================
```{r issue_summary}
substitute_emoji <- function(x) {
  m <- gregexpr(":[^[:space:]]+:", x)

  regmatches(x, m) <- lapply(regmatches(x, m), function(xx) map_chr(gsub(":", "", xx), emo::ji))
  x
}

# linkify the titles, and replace emoji
issue_table <- mutate(issues,
  title = glue::glue('<a rel="noopener" target="_blank" href="https://github.com/{owner}/{repo}/issues/{issue}">{title}</a>'),
  labels = substitute_emoji(map_chr(labels, paste, collapse = ", "))) %>%
  rename(!!p1 := p1)

# 0- owner, 1- repo, 2- issue, 3- title, 4- updated, 5- thumbs up, 6- labels
data_table(
  issue_table,
  list(
    order = list(
      list(4, "desc")  # updated from newest to oldest
    )))
# data_table(issue_table)
```

Unlabeled issues
====================================

```{r}
issue_table %>%
  filter(labels == "") %>%
  select(-labels) %>%
  data_table(
    list(
      order = list(
        list(4, "asc")  # updated from oldest to newest
      )
    )
  )

```

`r duration` pull request summary
=====================================


### PR authors
```{r}
data_table(pr_authors)
```

### PR reviewers
```{r}
data_table(pr_reviewers)
```

### PR pairs
```{r}
data_table(pr_pairs)
```
